name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v -c release --arch arm64 --arch x86_64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: .build/apple/Products/Release/mac-ocr-cli
